### ISSUE TITLE
Download AppImage

### ISSUE THREAD

**Issue by probonopd** [DomDumont/CartaGen#2]
Where can the AppImage be downloaded? It gets built on Travis CI. Is it uploaded somewhere?

**Comment by DomDumont** [comment]
Hi, this project currently does absolutely nothing. I'm trying to redo an old side project from scratch. But, you're right, the build process is quite ready and the future appimages will be posted here :

[https://domdumont.itch.io/cartagen](https://domdumont.itch.io/cartagen)

**Comment by DomDumont** [comment]
Hi @probonopd FYI there will be some new linux builds here very soon : https://domdumont.itch.io/cartagen
