### ISSUE TITLE
[Bug] Couldn't Change Font

### ISSUE THREAD

**Issue by Josanshuo** [DomDumont/CartaGen#4]
I couldn't change the font for text, but changing font size is okay. Here are the log:

![image](https://user-images.githubusercontent.com/42686700/224452160-b8594b02-2f74-4f07-a457-5ff65dfcf6f6.png)

Version: win-0.3.0
OS: Win10

Please let me know if more info is needed.

PS: feel it would be better to create different issues to separate topics :)

**Comment by DomDumont** [comment]
will check

**Comment by DomDumont** [comment]
should be fixed
