### ISSUE TITLE
[Feature Request] Option to toggle on/off grid in sheet

### ISSUE THREAD

**Issue by Josanshuo** [DomDumont/CartaGen#6]
The grid is good for cutting cards on printed papers, but it could show a strange boarder in TTS.

![image](https://user-images.githubusercontent.com/42686700/224453546-66c53c73-6f30-4846-8013-57137d3ccf4c.png)

The following issue is also caused by the sheet size is not adjustable, but show the screenshoot in TTS to show the boarder issue:

![image](https://user-images.githubusercontent.com/42686700/224454304-345585ca-fe55-446d-bfc9-d4c152e58b24.png)

**Comment by DomDumont** [comment]
I will do this option but again i do not understand how you end up with 8 cards in TTS format. TTS format is huge and you can only fit one card on an A4 paper size sheet

**Comment by Josanshuo** [comment]
My understand is the TTS accepts an image for custom deck, and user could deceide how many cards in that image (row, column, and number): 
![image](https://user-images.githubusercontent.com/42686700/224871284-b643efa5-05a2-42c8-8dc8-a57779bdd52f.png)

Possbibly it is not a feature for sheet, as it mainly is for printting. I will create a separate feature request.

**Comment by Josanshuo** [comment]
Oh actually the #8 is the feature request.

**Comment by DomDumont** [comment]
Done, the option is located in the sheet property page
