### ISSUE TITLE
[Bug] Not responding after set the Show Grid perfernce

### ISSUE THREAD

**Issue by Josanshuo** [DomDumont/CartaGen#7]
![image](https://user-images.githubusercontent.com/42686700/224454673-0a06f9db-a5ae-423a-9ecd-3b669b32a6d7.png)

Check the `Show Grid` option, then close the dialog, the entire window becomes not responding. But if the option is not checked, then closing the dialog won't cause any issue.

Also other perfernce options won't have any issue no matter toggle on or off, including the font changes.

**Comment by DomDumont** [comment]
In fact, it's not the Show Grid that causes problems, it's the 0 ( the grid size )

**Comment by DomDumont** [comment]
Fixed
