### ISSUE TITLE
[Feature Request] Support export multiple cards on one picture

### ISSUE THREAD

**Issue by Josanshuo** [DomDumont/CartaGen#8]
TTS support customizing deck, the template and editor could be found [here](https://kb.tabletopsimulator.com/custom-content/custom-deck/#card-sheet-template)(the row X col doesn't need to be 10x7, could be any combaination bigger than 2x2 but smaller than 10x7):

![image](https://user-images.githubusercontent.com/42686700/224484384-aed23a0c-beca-458c-b34d-75613207bc95.png)

In current sheet feature, it is good for pinted cards, but I couldn't set it's format to meet the TTS custom deck template, like fully remove the margin. 

Related feature request would be removing the grid in sheet: #6

**Comment by DomDumont** [comment]
Should be ok with the new 0.4.0 on itch.io.  @Josanshuo do not hesitate to tell me if it suits you
