### ISSUE TITLE
[Bug] Print Preview crashes when clicked without any project opens

### ISSUE THREAD

**Issue by Josanshuo** [DomDumont/CartaGen#9]
Feel the print preview should be disabled when no card or sheet is selected.

**Comment by DomDumont** [comment]
now print is only available as a right-click action on cards and sheets

**Comment by Josanshuo** [comment]
Thank you for the quick fixes! Wondering is there any release plan for them?

**Comment by DomDumont** [comment]
Probably tomorrow, stay tuned
